require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExpedientsController do

  # This should return the minimal set of attributes required to create a valid
  # Expedient. As you add validations to Expedient, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:start_time => Time.zone.now, :end_time => Time.zone.now+1.hour, :quantity_lessons => 3}
  end

  describe "GET index" do
    it "assigns all expedients as @expedients" do
      expedient = Expedient.create! valid_attributes
      get :index
      assigns(:expedients).should eq([expedient])
    end
  end

  describe "GET show" do
    it "assigns the requested expedient as @expedient" do
      expedient = Expedient.create! valid_attributes
      get :show, :id => expedient.id
      assigns(:expedient).should eq(expedient)
    end
  end

  describe "GET new" do
    it "assigns a new expedient as @expedient" do
      get :new
      assigns(:expedient).should be_a_new(Expedient)
    end
  end

  describe "GET edit" do
    it "assigns the requested expedient as @expedient" do
      expedient = Expedient.create! valid_attributes
      get :edit, :id => expedient.id
      assigns(:expedient).should eq(expedient)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Expedient" do
        expect {
          post :create, :expedient => valid_attributes
        }.to change(Expedient, :count).by(1)
      end

      it "assigns a newly created expedient as @expedient" do
        post :create, :expedient => valid_attributes
        assigns(:expedient).should be_a(Expedient)
        assigns(:expedient).should be_persisted
      end

      it "redirects to the created expedient" do
        post :create, :expedient => valid_attributes
        response.should redirect_to(Expedient.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved expedient as @expedient" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expedient.any_instance.stub(:save).and_return(false)
        post :create, :expedient => {}
        assigns(:expedient).should be_a_new(Expedient)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Expedient.any_instance.stub(:save).and_return(false)
        post :create, :expedient => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested expedient" do
        expedient = Expedient.create! valid_attributes
        # Assuming there are no other expedients in the database, this
        # specifies that the Expedient created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Expedient.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => expedient.id, :expedient => {'these' => 'params'}
      end

      it "assigns the requested expedient as @expedient" do
        expedient = Expedient.create! valid_attributes
        put :update, :id => expedient.id, :expedient => valid_attributes
        assigns(:expedient).should eq(expedient)
      end

      it "redirects to the expedient" do
        expedient = Expedient.create! valid_attributes
        put :update, :id => expedient.id, :expedient => valid_attributes
        response.should redirect_to(expedient)
      end
    end

    describe "with invalid params" do
      it "assigns the expedient as @expedient" do
        expedient = Expedient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expedient.any_instance.stub(:save).and_return(false)
        put :update, :id => expedient.id, :expedient => {}
        assigns(:expedient).should eq(expedient)
      end

      it "re-renders the 'edit' template" do
        expedient = Expedient.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Expedient.any_instance.stub(:save).and_return(false)
        put :update, :id => expedient.id, :expedient => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested expedient" do
      expedient = Expedient.create! valid_attributes
      expect {
        delete :destroy, :id => expedient.id
      }.to change(Expedient, :count).by(-1)
    end

    it "redirects to the expedients list" do
      expedient = Expedient.create! valid_attributes
      delete :destroy, :id => expedient.id
      response.should redirect_to(expedients_url)
    end
  end

end
