require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimetablesController do
  let(:grid){ Factory.create(:grid_complete) }

  # This should return the minimal set of attributes required to create a valid
  # Timetable. As you add validations to Timetable, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :grid_id => grid.id,
      :name    => "timetable"
    }
  end

  describe "GET index" do
    it "assigns all timetables as @timetables" do
      timetable = Timetable.create! valid_attributes
      get :index
      assigns(:timetables).should eq([timetable])
    end
  end

  describe "GET show" do
    it "assigns the requested timetable as @timetable" do
      timetable = Timetable.create! valid_attributes
      get :show, :id => timetable.id
      assigns(:timetable).should eq(timetable)
    end
  end

  describe "GET new" do
    it "assigns a new timetable as @timetable" do
      get :new
      assigns(:timetable).should be_a_new(Timetable)
    end
  end

  describe "GET edit" do
    it "assigns the requested timetable as @timetable" do
      timetable = Timetable.create! valid_attributes
      get :edit, :id => timetable.id
      assigns(:timetable).should eq(timetable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Timetable" do
        expect {
          post :create, :timetable => valid_attributes
        }.to change(Timetable, :count).by(1)
      end

      it "assigns a newly created timetable as @timetable" do
        post :create, :timetable => valid_attributes
        assigns(:timetable).should be_a(Timetable)
        assigns(:timetable).should be_persisted
      end

      it "redirects to the created timetable" do
        post :create, :timetable => valid_attributes
        response.should redirect_to(Timetable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved timetable as @timetable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timetable.any_instance.stub(:save).and_return(false)
        post :create, :timetable => {}
        assigns(:timetable).should be_a_new(Timetable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Timetable.any_instance.stub(:save).and_return(false)
        post :create, :timetable => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested timetable" do
        timetable = Timetable.create! valid_attributes
        # Assuming there are no other timetables in the database, this
        # specifies that the Timetable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Timetable.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => timetable.id, :timetable => {'these' => 'params'}
      end

      it "assigns the requested timetable as @timetable" do
        timetable = Timetable.create! valid_attributes
        put :update, :id => timetable.id, :timetable => valid_attributes
        assigns(:timetable).should eq(timetable)
      end

      it "redirects to the timetable" do
        timetable = Timetable.create! valid_attributes
        put :update, :id => timetable.id, :timetable => valid_attributes
        response.should redirect_to(timetable)
      end
    end

    describe "with invalid params" do
      it "assigns the timetable as @timetable" do
        timetable = Timetable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timetable.any_instance.stub(:save).and_return(false)
        put :update, :id => timetable.id, :timetable => {}
        assigns(:timetable).should eq(timetable)
      end

      it "re-renders the 'edit' template" do
        timetable = Timetable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Timetable.any_instance.stub(:save).and_return(false)
        put :update, :id => timetable.id, :timetable => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested timetable" do
      timetable = Timetable.create! valid_attributes
      expect {
        delete :destroy, :id => timetable.id
      }.to change(Timetable, :count).by(-1)
    end

    it "redirects to the timetables list" do
      timetable = Timetable.create! valid_attributes
      delete :destroy, :id => timetable.id
      response.should redirect_to(timetables_url)
    end
  end

end
