require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimeGapsController do

  # This should return the minimal set of attributes required to create a valid
  # TimeGap. As you add validations to TimeGap, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :day_of_week       => "friday",
      :start_time        => Time.zone.local(2011, 12, 16,  9, 00, 00),
      :end_time          => Time.zone.local(2011, 12, 16, 10, 00, 00),
      :quantity_lessons  => 1
    }
  end
  
  def valid_attributes_for_api
    {
      "day_of_week"       =>  "wednesday",
      "start_time"        =>  "2011-12-16 08:00:00 UTC",
      "end_time"          =>  "2011-12-16 09:00:00 UTC",
      "quantity_lessons"  =>  "1"
    }
  end

  describe "GET index" do
    it "assigns all time_gaps as @time_gaps" do
      time_gap = TimeGap.create! valid_attributes
      get :index
      assigns(:time_gaps).should eq([time_gap])
    end
  end

  describe "GET show" do
    it "assigns the requested time_gap as @time_gap" do
      time_gap = TimeGap.create! valid_attributes
      get :show, :id => time_gap.id
      assigns(:time_gap).should eq(time_gap)
    end
  end

  describe "GET new" do
    it "assigns a new time_gap as @time_gap" do
      get :new
      assigns(:time_gap).should be_a_new(TimeGap)
    end
  end

  describe "GET edit" do
    it "assigns the requested time_gap as @time_gap" do
      time_gap = TimeGap.create! valid_attributes
      get :edit, :id => time_gap.id
      assigns(:time_gap).should eq(time_gap)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TimeGap" do
        expect {
          post :create, :time_gap => valid_attributes_for_api
        }.to change(TimeGap, :count).by(1)
      end

      it "assigns a newly created time_gap as @time_gap" do
        post :create, :time_gap => valid_attributes_for_api
        assigns(:time_gap).should be_a(TimeGap)
        assigns(:time_gap).should be_persisted
      end

      it "redirects to the created time_gap" do
        post :create, :time_gap => valid_attributes_for_api
        response.should redirect_to(TimeGap.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved time_gap as @time_gap" do
        # Trigger the behavior that occurs when invalid params are submitted
        TimeGap.any_instance.stub(:save).and_return(false)
        post :create, :time_gap => {}
        assigns(:time_gap).should be_a_new(TimeGap)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TimeGap.any_instance.stub(:save).and_return(false)
        post :create, :time_gap => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested time_gap" do
        time_gap = TimeGap.create! valid_attributes
        # Assuming there are no other time_gaps in the database, this
        # specifies that the TimeGap created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TimeGap.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => time_gap.id, :time_gap => {'these' => 'params'}
      end

      it "assigns the requested time_gap as @time_gap" do
        time_gap = TimeGap.create! valid_attributes
        put :update, :id => time_gap.id, :time_gap => valid_attributes_for_api
        assigns(:time_gap).should eq(time_gap)
      end

      it "redirects to the time_gap" do
        time_gap = TimeGap.create! valid_attributes
        put :update, :id => time_gap.id, :time_gap => valid_attributes_for_api
        response.should redirect_to(time_gap)
      end
    end

    describe "with invalid params" do
      it "assigns the time_gap as @time_gap" do
        time_gap = TimeGap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TimeGap.any_instance.stub(:save).and_return(false)
        put :update, :id => time_gap.id, :time_gap => {}
        assigns(:time_gap).should eq(time_gap)
      end

      it "re-renders the 'edit' template" do
        time_gap = TimeGap.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TimeGap.any_instance.stub(:save).and_return(false)
        put :update, :id => time_gap.id, :time_gap => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested time_gap" do
      time_gap = TimeGap.create! valid_attributes
      expect {
        delete :destroy, :id => time_gap.id
      }.to change(TimeGap, :count).by(-1)
    end

    it "redirects to the time_gaps list" do
      time_gap = TimeGap.create! valid_attributes
      delete :destroy, :id => time_gap.id
      response.should redirect_to(time_gaps_url)
    end
  end

end
